### ISSUE TITLE
Recorder: app crashes when starting

### ISSUE THREAD

**Issue by drordotan** [drordotan/writracker#16]
When I start the app on my desktop, it crashes in the check_if_tablet_connected() function, when calling the PowerShell command - i.e. this line of code:
    device_list = subprocess.getoutput(
        "PowerShell -Command \"& {Get-PnpDevice | Select-Object Status,FriendlyName | ConvertTo-Json}\"")

This is the error I get. It seems that the returned value contains a character that is invalid for the assumed character mapping.

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/git/writracker/wacom_recorder/recorder.py", line 759, in <module>
    check_if_tablet_connected()
  File "E:/git/writracker/wacom_recorder/recorder.py", line 742, in check_if_tablet_connected
    "PowerShell -Command \"& {Get-PnpDevice | Select-Object Status,FriendlyName | ConvertTo-Json}\"")
  File "C:\Program Files (x86)\Python37-32\lib\subprocess.py", line 605, in getoutput
    return getstatusoutput(cmd)[1]
  File "C:\Program Files (x86)\Python37-32\lib\subprocess.py", line 586, in getstatusoutput
    data = check_output(cmd, shell=True, text=True, stderr=STDOUT)
  File "C:\Program Files (x86)\Python37-32\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Program Files (x86)\Python37-32\lib\subprocess.py", line 474, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Program Files (x86)\Python37-32\lib\subprocess.py", line 926, in communicate
    stdout = self.stdout.read()
  File "C:\Program Files (x86)\Python37-32\lib\encodings\cp1255.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8e in position 13974: character maps to <undefined>

**Comment by drordotan** [comment]
Ron, If you need to reproduce it, I can connect you to my computer with TeamViewer / remote desktop

**Comment by Dirskin** [comment]
was it fixed in: e189764d272e1c678cd2a02c7698e5703d1144c2
or it's a different issue?

**Comment by drordotan** [comment]
No, this still happens. e189764 was a fix for mac, but my desktop is Windows, not mac.

**Comment by drordotan** [comment]
It happens also on Maya's computer. Here's her stack trace:

C:\Python38-32\python.exe C:/writracker/src/wacom_recorder/recorder.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:/writracker/src/wacom_recorder/recorder.py", line 963, in <module>
    check_if_tablet_connected()
  File "C:/writracker/src/wacom_recorder/recorder.py", line 916, in check_if_tablet_connected
    return check_if_tablet_connected_windows()
  File "C:/writracker/src/wacom_recorder/recorder.py", line 941, in check_if_tablet_connected_windows
    device_list = subprocess.getoutput(
  File "C:\Python38-32\lib\subprocess.py", line 631, in getoutput
    return getstatusoutput(cmd)[1]
  File "C:\Python38-32\lib\subprocess.py", line 612, in getstatusoutput
    data = check_output(cmd, shell=True, text=True, stderr=STDOUT)
  File "C:\Python38-32\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python38-32\lib\subprocess.py", line 491, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Python38-32\lib\subprocess.py", line 1011, in communicate
    stdout = self.stdout.read()
  File "C:\Python38-32\lib\encodings\cp1255.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8e in position 281: character maps to <undefined>

**Comment by Dirskin** [comment]
I'm closing this bug, because 4aadc1c fixes the crash.
I opened a new issue (#43) to improve the tablet connection check, preferably without powershell dependency.
