### ISSUE TITLE
Encoder: ESC should abort any command

### ISSUE THREAD

**Issue by drordotan** [drordotan/writracker#63]
- Selecting a character/stroke
- Split-stroke screen

**Comment by rl100** [comment]
Fixed

**Comment by drordotan** [comment]
Still doesn't consistently work on mac. 
On mac, the escape event string is not "Escape:27" but a single character that is ASCII 27.
So the condition should be
event == 'Escape:27' or (isinstance(event, str) and len(event) == 1 and ord(event) == 27)

I added this to one place in trialcoder.py
